[workspace]
members = ["crates/*"]
repository = "https://github.com/vanilla-extracts/various_project.git"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
