[package]
name = "ls"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/vanilla-extracts/various_projects.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
